# Generated by Django 4.1.3 on 2022-11-02 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Баланс:')),
                ('moment', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда:')),
            ],
        ),
    ]
