# Generated by Django 4.1.3 on 2022-11-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название организации')),
                ('chat_id', models.IntegerField(verbose_name='ID группы в Телеграм')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='ID участника в Телеграм')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='manage_bots.telegramorganisation', verbose_name='Компания пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='manage_bots.telegramorganisation', verbose_name='Компания-клиент'),
            preserve_default=False,
        ),
    ]
