# Generated by Django 4.1.3 on 2022-11-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0002_telegramorganisation_telegramuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='organisation',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_bot_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_notification_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ник в ТГ'),
        ),
        migrations.DeleteModel(
            name='TelegramOrganisation',
        ),
    ]
