# Generated by Django 4.1.3 on 2022-11-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0003_remove_balance_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_bot_user',
            field=models.BooleanField(default=True, verbose_name='Видит баланс'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_notification_list',
            field=models.BooleanField(default=False, verbose_name='Получает уведомление'),
        ),
    ]
