# Generated by Django 4.1.3 on 2022-11-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0004_alter_telegramuser_is_bot_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название бота')),
                ('type', models.CharField(max_length=50, verbose_name='Тип бота')),
                ('first_limit', models.IntegerField(default=5000, verbose_name='Первый предел')),
                ('first_limit_delay', models.IntegerField(default=12, verbose_name='Периодичность уведомления в часах')),
                ('critical_limit', models.IntegerField(default=2000, verbose_name='Первый предел')),
                ('critical_limit_delay', models.IntegerField(default=1, verbose_name='Периодичность уведомления в часах')),
            ],
        ),
    ]
