# Generated by Django 4.1.3 on 2022-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0006_telegramgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='api_requests_interval',
            field=models.IntegerField(default=60, verbose_name='Частота обновления по АПИ в секундах'),
        ),
    ]
