# Generated by Django 4.1.3 on 2022-11-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0007_bot_api_requests_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='type',
        ),
    ]
