# Generated by Django 4.1.3 on 2022-11-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_bots', '0008_remove_bot_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'баланс', 'verbose_name_plural': 'балансы'},
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'бот', 'verbose_name_plural': 'боты'},
        ),
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={'verbose_name': 'ТГ группа', 'verbose_name_plural': 'ТГ группы'},
        ),
    ]
